[hugoVersion]
extended = true
min = "0.95.0"


[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/table-of-contents"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/youtube-lite"